[package]
name = "to_do_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
serde = {version = "1.0.213", features = ["derive"]}
clap = { version = "4.5.20", features = ["derive"] }
